server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - '' # Origen permitido para el frontend
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "*"
            allow-credentials: true # Permite cookies y autenticación
      default-filters:
        - RewritePath /USER-SERVICE/?(?<remaining>.*) = '/${remaining}'
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*),/api/v1/users/${segment}
          
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
          filters:
            - RewritePath=/loan/(?<segment>.*),/api/v1/loans/${segment}

        - id: userLoan-service
          uri: lb://userLoan-service
          predicates:
            - Path=/userLoan/**
          filters:
            - RewritePath=/userLoan/(?<segment>.*),/api/v1/userLoans/${segment}
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG