server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]'
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allos-credentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: userLoan-service
          uri: lb://userLoan-service
          predicates:
            - Path=/userLoan/**