server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA}:8761/eureka/
  instance:
    hostname: eureka-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]'
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allos-credentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*),/api/v1/users/${segment}
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
          filters:
            - RewritePath=/loan/(?<segment>.*),/api/v1/loans/${segment}
        - id: userLoan-service
          uri: lb://userLoan-service
          predicates:
            - Path=/userLoan/**
          filters:
            - RewritePath=/userLoan/(?<segment>.*),/api/v1/userLoans/${segment}