server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  cloud:
    inetutils:
      timeout-seconds: 5
      default-hostname: eureka-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}